# Generated by Django 5.0.6 on 2026-03-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("navigation_label", models.CharField(max_length=100)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("LANDING", "Landing"),
                            ("CALCULATOR", "Calculator"),
                            ("CONTACT", "Contact"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=200)),
                ("hero_title", models.CharField(max_length=255)),
                ("hero_description", models.TextField(blank=True)),
                ("hero_primary_cta_text", models.CharField(blank=True, max_length=100)),
                ("hero_primary_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "hero_secondary_cta_text",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "hero_secondary_cta_url",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="website/hero/"),
                ),
                ("hero_image_alt", models.CharField(blank=True, max_length=200)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("seo_description", models.TextField(blank=True)),
                ("show_in_nav", models.BooleanField(default=True)),
                ("nav_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nav_order", "navigation_label"],
            },
        ),
        migrations.CreateModel(
            name="WebsitePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("CARD_GRID", "Card Grid"),
                            ("FEATURE_LIST", "Feature List"),
                            ("STATS", "Stats"),
                            ("CTA", "Call To Action"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("ALT", "Alt Background"),
                            ("HIGHLIGHT", "Highlight"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/sections/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="website.websitepage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebsitePageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("badge", models.CharField(blank=True, max_length=120)),
                ("value", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/blocks/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="website.websitepagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
