# Generated by Django 5.0.6 on 2026-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_websitepage_websitepagesection_websitepageblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitesettings",
            name="client_portal_url",
            field=models.CharField(default="/app/", max_length=255),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="hero_primary_cta_url",
            field=models.CharField(default="/app/", max_length=255),
        ),
    ]
