# Generated by Django 6.0.2 on 2026-02-18 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat Rate'), ('REDUCING', 'Reducing Balance'), ('DAILY', 'Daily Rate'), ('MONTHLY', 'Monthly Rate')], default='FLAT', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nominal_interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('credit_facilitation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_term', models.IntegerField()),
                ('max_term', models.IntegerField()),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('grace_period_days', models.IntegerField(default=3)),
                ('rollover_interest_rate', models.DecimalField(decimal_places=2, default=4, max_digits=6)),
                ('max_rollovers', models.IntegerField(default=2)),
                ('rollover_min_principal_paid_percent', models.IntegerField(default=30)),
                ('rollover_extension_days', models.IntegerField(default=14)),
                ('required_documents', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('nrc_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('credit_score', models.IntegerField(default=0)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self Employed'), ('BUSINESS_OWNER', 'Business Owner'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired')], default='EMPLOYED', max_length=20)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relation', models.CharField(blank=True, max_length=100)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('completed_loans', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_limit_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.loanproduct')),
            ],
            options={
                'unique_together': {('product', 'tier')},
            },
        ),
    ]
