# Generated by Django 5.0.6 on 2026-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('nrc_number', models.CharField(max_length=50, unique=True)),
                ('date_qualified', models.DateField(auto_now_add=True)),
                ('amount_qualified_for', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'ordering': ['-date_qualified'],
            },
        ),
    ]
