# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kycsection_kycfield_kycsubmission_kycfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
