# Generated by Django 5.0.6 on 2026-03-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_systemconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="repayment_frequency",
            field=models.CharField(
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("BIWEEKLY", "Bi-Weekly (Every 2 Weeks)"),
                    ("MONTHLY", "Monthly"),
                ],
                default="MONTHLY",
                max_length=10,
            ),
        ),
    ]
