# Generated by Django 5.0.6 on 2026-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_repayment_frequency_to_loanproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                default="",
                max_length=10,
            ),
        ),
    ]
