# Generated by Django 5.0.6 on 2026-03-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
