# Generated by Django 6.0.2 on 2026-02-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose', models.CharField(max_length=500)),
                ('term_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('WRITTEN_OFF', 'Written Off')], default='PENDING_APPROVAL', max_length=20)),
                ('documents', models.JSONField(default=list)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_repayable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ptp_status', models.CharField(choices=[('NONE', 'None'), ('ACTIVE', 'Active'), ('BROKEN', 'Broken'), ('FULFILLED', 'Fulfilled')], default='NONE', max_length=10)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('ptp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rollover_count', models.IntegerField(default=0)),
                ('rollover_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('days_overdue', models.IntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CALL', 'Phone Call'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('FIELD_VISIT', 'Field Visit'), ('PTP_PROMISE', 'Promise to Pay'), ('LEGAL_NOTICE', 'Legal Notice'), ('WRITE_OFF_REQUEST', 'Write-off Request')], max_length=20)),
                ('agent_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=500)),
                ('ptp_date', models.DateField(blank=True, null=True)),
                ('ptp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to='loans.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Disbursement'), ('REPAYMENT', 'Repayment'), ('PENALTY', 'Penalty'), ('ROLLOVER_FEE', 'Rollover Fee'), ('SETTLEMENT', 'Settlement'), ('WRITE_OFF', 'Write Off')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('posted_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
