# Generated by Django 5.0 — Section 10 Konse Konse payment gateway integration
# NOTE: Account codes 1106/2110 are already in use; KK accounts are 1107/1108/2111/5223.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_odoo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'loan',
                    models.ForeignKey(
                        blank=True,
                        help_text='Related LMS loan (null for gateway-level transactions not yet matched to a loan).',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='konse_transactions',
                        to='loans.loan',
                    ),
                ),
                (
                    'transaction_reference',
                    models.CharField(
                        help_text='Konse Konse transaction reference (e.g. KK-20260316-ABC123).',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'transaction_type',
                    models.CharField(
                        choices=[
                            ('DISBURSEMENT', 'Disbursement'),
                            ('REPAYMENT', 'Repayment'),
                            ('FEE', 'Fee Collection'),
                            ('AGENT_COLLECTION', 'Agent Collection'),
                        ],
                        help_text='Type of KK transaction.',
                        max_length=20,
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='ZMW transaction amount.',
                        max_digits=15,
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        default='ZMW',
                        help_text='ISO 4217 currency code; always ZMW for Zambia.',
                        max_length=3,
                    ),
                ),
                (
                    'mobile_number',
                    models.CharField(
                        blank=True,
                        help_text='Borrower/payer mobile number.',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('CONFIRMED', 'Confirmed'),
                            ('FAILED', 'Failed'),
                            ('DUPLICATE', 'Duplicate'),
                        ],
                        db_index=True,
                        default='PENDING',
                        help_text='Current processing status.',
                        max_length=20,
                    ),
                ),
                (
                    'odoo_move_id',
                    models.IntegerField(
                        blank=True,
                        help_text='Odoo account.move ID created when this transaction was posted.',
                        null=True,
                    ),
                ),
                (
                    'odoo_invoice_id',
                    models.IntegerField(
                        blank=True,
                        help_text='Odoo account.move (invoice) ID reconciled against this payment.',
                        null=True,
                    ),
                ),
                (
                    'konse_raw_payload',
                    models.JSONField(
                        blank=True,
                        help_text='Raw JSON payload received from the KK webhook or polling API.',
                        null=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'processed_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the transaction reached a terminal status (CONFIRMED/FAILED).',
                        null=True,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='konsetransaction',
            index=models.Index(fields=['loan'], name='loans_konse_loan_id_idx'),
        ),
        migrations.AddIndex(
            model_name='konsetransaction',
            index=models.Index(fields=['transaction_reference'], name='loans_konse_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='konsetransaction',
            index=models.Index(fields=['status'], name='loans_konse_status_idx'),
        ),
    ]
