# Generated by Django 5.0.6 on 2026-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_konse_transaction"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="konsetransaction",
            new_name="loans_konse_loan_id_6da572_idx",
            old_name="loans_konse_loan_id_idx",
        ),
        migrations.RenameIndex(
            model_name="konsetransaction",
            new_name="loans_konse_transac_6eb6cb_idx",
            old_name="loans_konse_ref_idx",
        ),
        migrations.RenameIndex(
            model_name="konsetransaction",
            new_name="loans_konse_status_3ca8fe_idx",
            old_name="loans_konse_status_idx",
        ),
        migrations.AddField(
            model_name="loan",
            name="client_info_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="client_info_response_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="info_request_by",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="loan",
            name="info_request_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="info_request_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="konsetransaction",
            name="currency",
            field=models.CharField(
                default="ZMW",
                help_text="ISO 4217 currency code; always ZMW for ZambiaZambia.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("PENDING_INFO", "Pending Information"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("OVERDUE", "Overdue"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("WRITTEN_OFF", "Written Off"),
                ],
                default="PENDING_APPROVAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DISBURSEMENT", "Disbursement"),
                    ("REPAYMENT", "Repayment"),
                    ("PENALTY", "Penalty"),
                    ("ROLLOVER_FEE", "Rollover Fee"),
                    ("SETTLEMENT", "Settlement"),
                    ("WRITE_OFF", "Write Off"),
                    ("RECOVERY", "Recovery"),
                ],
                max_length=20,
            ),
        ),
    ]
