# Generated by Django 5.0.6 on 2026-04-27 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_add_loan_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="CGRateTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DISBURSEMENT", "Disbursement"),
                            ("COLLECTION", "Collection"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("currency", models.CharField(default="ZMW", max_length=3)),
                (
                    "service",
                    models.CharField(
                        choices=[("MTN", "MTN"), ("Airtel", "Airtel")], max_length=20
                    ),
                ),
                (
                    "checklink",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("external_ref", models.CharField(blank=True, max_length=100)),
                ("response_message", models.TextField(blank=True)),
                ("raw_request", models.JSONField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cgrate_transactions",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["loan"], name="loans_cgrat_loan_id_cfbd2a_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="loans_cgrat_referen_fb5f45_idx"
                    ),
                    models.Index(
                        fields=["status"], name="loans_cgrat_status_0de936_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="loans_cgrat_transac_7415f0_idx",
                    ),
                ],
            },
        ),
    ]
