# Generated by Django 5.0.6 on 2026-03-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicLoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat Rate"),
                            ("REDUCING", "Reducing Balance"),
                        ],
                        default="FLAT",
                        max_length=10,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "nominal_interest_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "credit_facilitation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("min_term", models.IntegerField()),
                ("max_term", models.IntegerField()),
                ("required_documents", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("badge", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("CIVIL_SERVANT", "Civil Servant"),
                            ("TEACHER_OR_NURSE", "Teacher or Nurse"),
                            ("SALARIED_EMPLOYEE", "Salaried Employee"),
                            ("BUSINESS_OWNER", "Business Owner"),
                            ("OTHER", "Other"),
                        ],
                        default="CIVIL_SERVANT",
                        max_length=30,
                    ),
                ),
                ("employer_name", models.CharField(blank=True, max_length=200)),
                (
                    "desired_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "desired_term_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("message", models.TextField(blank=True)),
                ("consent", models.BooleanField(default=False)),
                ("source_page", models.CharField(default="website", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("CONVERTED", "Converted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebsitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("navigation_label", models.CharField(max_length=100)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("LANDING", "Landing"),
                            ("CALCULATOR", "Calculator"),
                            ("CONTACT", "Contact"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=200)),
                ("hero_title", models.CharField(max_length=255)),
                ("hero_description", models.TextField(blank=True)),
                ("hero_primary_cta_text", models.CharField(blank=True, max_length=100)),
                ("hero_primary_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "hero_secondary_cta_text",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "hero_secondary_cta_url",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="website/hero/"),
                ),
                ("hero_image_alt", models.CharField(blank=True, max_length=200)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("seo_description", models.TextField(blank=True)),
                ("show_in_nav", models.BooleanField(default=True)),
                ("nav_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nav_order", "navigation_label"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="IntZam", max_length=100)),
                (
                    "site_tagline",
                    models.CharField(
                        default="Smart Lending for Growing Communities", max_length=200
                    ),
                ),
                ("country_name", models.CharField(default="Zambia", max_length=100)),
                (
                    "hero_eyebrow",
                    models.CharField(
                        default="Fast. Clear. Human-centered lending.", max_length=200
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Beautiful digital lending for everyday ambition.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="IntZam helps individuals and growing businesses access flexible loans with transparent pricing, simple onboarding, and a modern mobile-first experience."
                    ),
                ),
                (
                    "hero_primary_cta_text",
                    models.CharField(default="Start an application", max_length=100),
                ),
                (
                    "hero_primary_cta_url",
                    models.CharField(default="/client-pwa/", max_length=255),
                ),
                (
                    "hero_secondary_cta_text",
                    models.CharField(default="Explore products", max_length=100),
                ),
                (
                    "hero_secondary_cta_url",
                    models.CharField(default="/calculator/", max_length=255),
                ),
                (
                    "client_portal_url",
                    models.CharField(default="/client-pwa/", max_length=255),
                ),
                (
                    "staff_portal_url",
                    models.CharField(default="/admin-frontend/", max_length=255),
                ),
                (
                    "zambia_focus_copy",
                    models.CharField(
                        default="Designed for Zambia's civil servants, salaried professionals, and growing households.",
                        max_length=255,
                    ),
                ),
                (
                    "audience_intro",
                    models.TextField(
                        default="Especially relevant for civil servants, teachers, nurses, and other dependable earners who need a simpler, more respectful lending experience."
                    ),
                ),
                (
                    "lead_form_title",
                    models.CharField(
                        default="Talk to IntZam about the right loan for you.",
                        max_length=255,
                    ),
                ),
                (
                    "lead_form_description",
                    models.TextField(
                        default="Share a few details and our team can reach out, especially if you are a civil servant or salaried professional in Zambia."
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(default="hello@intzam.com", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+260 000 000 000", max_length=30),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Website settings",
            },
        ),
        migrations.CreateModel(
            name="WebsiteTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WebsitePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("CARD_GRID", "Card Grid"),
                            ("FEATURE_LIST", "Feature List"),
                            ("STATS", "Stats"),
                            ("CTA", "Call To Action"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("ALT", "Alt Background"),
                            ("HIGHLIGHT", "Highlight"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/sections/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cms.websitepage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WebsitePageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("badge", models.CharField(blank=True, max_length=120)),
                ("value", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="website/blocks/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.websitepagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
