# Generated by Django 5.0.6 on 2026-03-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitesettings",
            name="staff_portal_url",
        ),
    ]
