# Generated by Django 5.0.6 on 2026-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_remove_websitesettings_staff_portal_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitepage",
            name="illustration_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="website/illustrations/"
            ),
        ),
        migrations.AddField(
            model_name="websitepage",
            name="illustration_image_alt",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
