# Generated by Django 5.0.6 on 2026-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_websitepage_illustration_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitepagesection",
            name="layout",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("CARD_GRID", "Card Grid"),
                    ("FEATURE_LIST", "Feature List"),
                    ("STATS", "Stats"),
                    ("CTA", "Call To Action"),
                    ("TEAM", "Team Grid"),
                    ("PHOTO_GRID", "Photo Grid"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
