# Generated by Django 5.0.6 on 2026-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_add_team_photo_grid_layouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="company_registration",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="facebook_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="linkedin_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="physical_address",
            field=models.CharField(
                blank=True, default="Lusaka, Zambia", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="regulatory_body",
            field=models.CharField(
                blank=True, default="Bank of Zambia", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="regulatory_licence",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="whatsapp_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
